[package]
name = "HugoDoc"
version = "0.1.0"
edition = "2024"
description = "A crate to generate markdown files from documentation written as comments directly inside the hugo directory for hosting"
license = "MIT"
repository = "https://github.com/n0th9ng2311/HugoDoc"

[dependencies]
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
walkdir = "2.5"
anyhow = "1.0"
clap = "4.6.6"