[hugo]
loc = "D:/"
title = "an example"
date = "2026-06-28"
author = "name"
tags = []
draft = "false"

[file_loc]
start = "<START FILE LOC>"
end = "<END FILE LOC>"

[ignore]
prefixes = ["// ", "# ", "/*", "*/"] #can add others later

[comment_types.simple_comment]
start = "!/!"
end = "!/!"
txt_type = "NORMAL"

[comment_types.heading]
start ="!!"
end = "!!"
txt_type = "HEADING"

[comment_types.warning]
start = "w!"
end = "!w"
txt_type = "NORMAL"